//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageUser.DbMain
{
    using System;
    using System.Collections.Generic;
    
    public partial class password
    {
        public string id { get; set; }
        public string user_id { get; set; }
        public string password1 { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> InsertYMD { get; set; }
    
        public virtual User User { get; set; }
    }
}
